const initialArray = [
  {
    cardName: "Tommy Shelby",
    cardDescription: "\"Do I look like a man, who wants a simple life?\" - Thomas Shelby",
    cardAttr1: "90",
    cardAttr2: "95",
    cardAttr3: "70",
    cardImage: "https://scontent.ffrc6-1.fna.fbcdn.net/v/t1.6435-9/167931485_295169715308398_3057534484445358024_n.jpg?_nc_cat=102&ccb=1-7&_nc_sid=09cbfe&_nc_eui2=AeHlAv4BM8s2SFEup6izetnPhY_vo3JVjVGFj--jclWNUXL8rSrljcuW267BPqESjIJQPL9gNSfnxnvs7nP6teaN&_nc_ohc=5K7NS52BMlEAX-0DcPn&tn=gfjJxGmbHGb7G6Jn&_nc_ht=scontent.ffrc6-1.fna&oh=00_AT9u36BHE-9PxVi_o4jb3t3hGqws6c2LiutsTHl50ozG5g&oe=62E122D7",
    cardRare: "gold",
    cardTrunfo: false,
  },
  {
    cardName: "Polly Gray",
    cardDescription: "\"You should call this painting Fuck Them All.\" - Polly Gray",
    cardAttr1: "40",
    cardAttr2: "85",
    cardAttr3: "75",
    cardImage: "https://i.pinimg.com/originals/20/62/d1/2062d131248173ec14a99e10e709dfeb.png",
    cardRare: "silver",
    cardTrunfo: false,
  },
  {
    cardName: "Arthur Shelby",
    cardDescription: "\"This place is under new management...by order of the Peaky Blinders!\" - Arthur Shelby",
    cardAttr1: "95",
    cardAttr2: "60",
    cardAttr3: "55",
    cardImage: "https://vader.news/__export/1614509110205/sites/gadgets/img/2021/02/28/arthur_shelby_peaky_blinders_1.jpg_1708672400.jpg",
    cardRare: "silver",
    cardTrunfo: false,
  },
  {
    cardName: "John Shelby",
    cardDescription: "\"Anyway, we're Peaky Blinders. We're not scared of coppers. If they come for us, we'll cut them a smile each.\" - John Shelby",
    cardAttr1: "75",
    cardAttr2: "60",
    cardAttr3: "35",
    cardImage: "https://rollingstone.uol.com.br/media/_versions/joe-cole-em-peaky-blinders_reproducao_twitter_widelg.jpg",
    cardRare: "normal",
    cardTrunfo: false,
  },
  {
    cardName: "Finn Shelby",
    cardDescription: "\"When me and the boys are feeling blue, this is what we do: it's called Tokyo.\" - Finn Shelby",
    cardAttr1: "70",
    cardAttr2: "50",
    cardAttr3: "50",
    cardImage: "https://images.immediate.co.uk/production/volatile/sites/3/2022/03/24312420-high_res-peaky-blinders-vi-186d660.jpg?resize=768,574",
    cardRare: "normal",
    cardTrunfo: false,
  },
  {
    cardName: "Michael Gray",
    cardDescription: "\"Fuck Off Arthur.\" - Michael Gray",
    cardAttr1: "70",
    cardAttr2: "65",
    cardAttr3: "45",
    cardImage: "https://www.thesun.co.uk/wp-content/uploads/2020/09/Michael-Gray-2662471.jpg",
    cardRare: "normal",
    cardTrunfo: false,
  },
  {
    cardName: "Aberama Gold",
    cardDescription: "\"Everything is for sale. Everything.\" - Aberama Gold",
    cardAttr1: "80",
    cardAttr2: "75",
    cardAttr3: "70",
    cardImage: "https://i.pinimg.com/originals/dd/25/b5/dd25b5da890866816f393cc4173236ba.jpg",
    cardRare: "silver",
    cardTrunfo: false,
  },
  {
    cardName: "Alfie Salomons",
    cardDescription: "\"You're gypsies, right? So what do you live in, a fucking tent or caravan?\" - Alfie Solomons",
    cardAttr1: "85",
    cardAttr2: "90",
    cardAttr3: "75",
    cardImage: "https://i2-prod.birminghammail.co.uk/incoming/article11390310.ece/ALTERNATES/s1200b/JS91109894.jpg",
    cardRare: "gold",
    cardTrunfo: false,
  },
  {
    cardName: "Ada Thorne",
    cardDescription: "\"Oi! I'm a Shelby too, you know. Put my fucking film back on!\" - Ada Thorne",
    cardAttr1: "25",
    cardAttr2: "80",
    cardAttr3: "80",
    cardImage: "https://cdn.images.express.co.uk/img/dynamic/20/590x/peaky-blinders-sophie-rundle-ada-shelby-1417008.jpg?r=1617132387671",
    cardRare: "silver",
    cardTrunfo: false,
  },
  {
    cardName: "Billy Kimber",
    cardDescription: "\"Nobody works with me. People work for me.\" - Billy Kimber.",
    cardAttr1: "65",
    cardAttr2: "85",
    cardAttr3: "70",
    cardImage: "https://i2-prod.devonlive.com/incoming/article6493745.ece/ALTERNATES/s1200c/1_Screenshot-2022-01-14-at-140939.png",
    cardRare: "silver",
    cardTrunfo: false,
  },
  {
    cardName: "Bonnie Gold",
    cardDescription: "\"I could fight a fucking tree and knock it out, Mr Shelby.\" - Bonnie Gold",
    cardAttr1: "100",
    cardAttr2: "50",
    cardAttr3: "30",
    cardImage: "https://pbs.twimg.com/media/DztsMmuXcAI6WFs.jpg",
    cardRare: "normal",
    cardTrunfo: false,
  },
  {
    cardName: "Esme Shelby",
    cardDescription: "\"Your Gypsy half is the stronger.\" - Esme Shelby",
    cardAttr1: "35",
    cardAttr2: "70",
    cardAttr3: "70",
    cardImage: "https://i2-prod.walesonline.co.uk/incoming/article23423440.ece/ALTERNATES/s1200c/1_24306712-low_res-peaky-blinders-vi.jpg",
    cardRare: "normal",
    cardTrunfo: false,
  },
  {
    cardName: "Inspector Campbell",
    cardDescription: "\"God help those who stand in our way!\" - Inspector Campbell",
    cardAttr1: "65",
    cardAttr2: "75",
    cardAttr3: "70",
    cardImage: "https://tvserieswelove.com/wp-content/uploads/2019/10/1549401702593.jpg",
    cardRare: "normal",
    cardTrunfo: false,
  },
  {
    cardName: "Jeremiah Jesus",
    cardDescription: "\"“God says he don't mess with Small Heath.”\" - Jeremiah Jesus",
    cardAttr1: "75",
    cardAttr2: "75",
    cardAttr3: "85",
    cardImage: "https://i.guim.co.uk/img/media/11cb53e06491213b02d7f6143f09524c7db5c844/0_39_4284_2572/master/4284.jpg?width=465&quality=45&auto=format&fit=max&dpr=2&s=840a2caf73b45c9c3dbdc551e1bf0cbf",
    cardRare: "normal",
    cardTrunfo: false,
  },
  {
    cardName: "Johnny Dogs",
    cardDescription: "\"Oh, fuck, Tom. I thought your sporting days were over?\" - Johnny Dogs",
    cardAttr1: "65",
    cardAttr2: "50",
    cardAttr3: "55",
    cardImage: "https://vader.news/__export/1609017075642/sites/gadgets/img/2020/12/26/johnny_dogs.jpg_500629916.jpg",
    cardRare: "normal",
    cardTrunfo: false,
  },
  {
    cardName: "Oswald Mosley",
    cardDescription: "\"I am going to fuck the swan, tonight.\" - Oswald Mosley",
    cardAttr1: "70",
    cardAttr2: "100",
    cardAttr3: "75",
    cardImage: "https://listasnerds.com.br/wp-content/uploads/2022/03/oswald-mosley-peaky-blinders-850x560.png",
    cardRare: "gold",
    cardTrunfo: false,
  },
];

export default initialArray;
